### PR TITLE
Fixed displaying of size for empty files.

### PR DESCRIPTION
**Pull request by christer**
Empty files was treated as directories and a - was show instead of 0 in
the size column.

### CODE REVIEW

**Comment by general03** [comment]
Hi @christer ,
Thanks for you contribution but I don't want display 0 on folder row.
It's more readable with "-", the UI is simpler

**Comment by christer** [comment]
To be clear, I didn't suggest displaying 0 or folder row. It's files with size 0 that got treated as directories i found odd.

**Comment by general03** [comment]
Sorry, I open again this issue

**Comment by general03** [comment]
I can't reproduce your issue, can you send me your UI diff
Thanks

**Pull request closed without merging**
